CREATE TABLE IF NOT EXISTS bookmarks (
  id VARCHAR PRIMARY KEY,
  url VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  tags VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_tags ON bookmarks (tags);