// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package sqlite

import (
	"time"

	"github.com/google/uuid"
)

type Bookmark struct {
	ID          uuid.UUID
	Url         string
	Description string
	Tags        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
