// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package sqlite

import (
	"time"
)

type Bookmark struct {
	ID          string
	Url         string
	Description string
	Tags        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
