// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Diary struct {
	ID        pgtype.UUID
	Day       pgtype.Date
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Task struct {
	ID        pgtype.UUID
	Title     string
	Content   string
	Status    string
	Tags      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type TaskDiary struct {
	TaskID  pgtype.UUID
	DiaryID pgtype.UUID
}
