// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Bookmark struct {
	ID          pgtype.UUID
	Url         string
	Description string
	Tags        string
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type Diary struct {
	ID        pgtype.UUID
	Day       pgtype.Date
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Note struct {
	ID        pgtype.UUID
	Title     string
	Content   string
	Tags      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
