// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: query.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDiary = `-- name: CreateDiary :one
INSERT INTO diary (id, day, created_at, updated_at) VALUES ($1, $2, $3, $4) RETURNING id, day, created_at, updated_at
`

type CreateDiaryParams struct {
	ID        pgtype.UUID
	Day       pgtype.Date
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

func (q *Queries) CreateDiary(ctx context.Context, arg CreateDiaryParams) (Diary, error) {
	row := q.db.QueryRow(ctx, createDiary,
		arg.ID,
		arg.Day,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Diary
	err := row.Scan(
		&i.ID,
		&i.Day,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
